### ISSUE TITLE
Prepack: list all parts being filtered out for Test262

### ISSUE THREAD

**Issue by leobalter** [bocoup/test262#129]
We should document all the parts being filtered out:

non-frontmatter filtering:

- Folders 
  - /intl402/:  test/intl402/
  - ~~/Date/prototype/to*/: test/build-ins/Date/prototype/to*/~~
  - /with/: test/language/statements/with/
  - /Atomics/: test/built-ins/Atomics/
  - /generators/: test/language/expressions/generators/, test/language/statements/generators/
  - /yield/: test/language/expressions/yield/
  - /module-code/: test/language/module-code/
  - /annexB/: test/annexB/
  - Function/prototype/toString: test/build-ins/Function/prototype/toString/
  - SharedArrayBuffer: test/built-ins/SharedArrayBuffer/
- file names (+ folders)
  - realm
  - tco (feature: tail-call-optimization)
  - U180
  - u180
  - mongolian
  - detached-buffer-after-toindex
  - detach-typedarray-in-progress.js
  - RegExp/S15.10.2.12_A1_T1.js
  - RegExp/S15.10.2.12_A2_T1.js
  - RegExp/prototype/Symbol.search/lastindex-no-restore
  - RegExp/prototype/exec/failure-lastindex-no-access.js
  - RegExp/prototype/exec/success-lastindex-no-access.js
  - Symbol.match/builtin-success-u-return-val-groups
  - sharedarraybuffer
  - StrictFunction_restricted-properties.js
- complicated
   - test.location.includes("/directive-prologue/") && testFileContents.includes("assert.throws(SyntaxError,")

frontmatter filtering:

```yaml
- esid:
  - pending
- negative `phase: early` tests
- features
  - tail-call-optimization
  - generators
  - default-parameters
- flags
  - async
- description
  - includes "Complex tests" # (decodeURI, encodeURI, decodeURIComponent, encodeURIComponent)
  - includes "iterating"
  - includes "itertable"
```

unnecessary:
```yaml
- es5id:
  - 7.8.5_A1.4_T2
  - 7.8.5_A2.4_T2
  - 7.8.5_A2.1_T2
  - 7.8.5_A1.1_T2
  - 15.1.2.2_A8
  - 15.1.2.3_A6
  - 7.4_A5
  - 7.4_A6
  - 15.10.2.12_A3_T1
  - 15.10.2.12_A4_T1
  - 15.10.2.12_A5_T1
  - 15.10.2.12_A6_T1
- es6id: 
  - 22.1.3.1_3 # Symbol.isConcatSpreadable
```

Question: can this be transformed into a data file (yaml?) to be consumed as a filter config for test262-harness?
