### ISSUE TITLE
test262 config file for filters (prototype)

### ISSUE THREAD

**Issue by leobalter** [bocoup/test262#134]
this depends on #129 

data.yaml:

```yaml
frontmatter: 
    esid: [ "pending" ]
    features: [ "sharedarraybuffer" ]
```
