### ISSUE TITLE
Identify really required filters for Prepack

### ISSUE THREAD

**Issue by leobalter** [bocoup/test262#136]
After discussing #129 we've found tests that are actually fine and don't need to be filtered out. They are also not really slow, I guess. 

We might need to investigate for more tests passing and the time they take to run.

---

### features/folders

- [ ] tail-call-optimization
- [ ] intl402 (folder)
- [ ] generators (feature + folders)
- [ ] yield (feature + folder)
- [ ] module-code (folder)
- [ ] Function.prototype.toString (folder)
- [ ] SharedArrayBuffer (feature + folder)
- [ ] atomics (feature + folder)
- [ ] cross-realm
- [ ] features still using `esid: pending` (BigInt, etc)

### Incompatibility with use strict + eval code: 

- test/language/directive-prologue/10.1.1-14-s.js
- test/language/directive-prologue/10.1.1-15-s.js
- test/language/directive-prologue/10.1.1-16-s.js
- test/language/directive-prologue/10.1.1-17-s.js
- test/language/directive-prologue/10.1.1-18-s.js
- test/language/directive-prologue/10.1.1-19-s.js
- test/language/directive-prologue/10.1.1-2-s.js
- test/language/directive-prologue/10.1.1-22-s.js
- test/language/directive-prologue/10.1.1-25-s.js
- test/language/directive-prologue/10.1.1-26-s.js
- test/language/directive-prologue/10.1.1-30-s.js
- test/language/directive-prologue/10.1.1-5-s.js
- test/language/directive-prologue/10.1.1-8-s.js

---

### confirm/skip:

- [ ] U+180E, Updated on Unicode 6.3.0, better to fail until it's covered(?)
- [ ] annex B, currently skipped, but partially supported (HTML-like comments, with, etc)

**Comment by leobalter** [comment]
investigating why Prepack filters out Symbol.isConcatSpreadable I found this: https://github.com/facebook/prepack/pull/673

**Comment by leobalter** [comment]
I changed the name to reflect on what is going to be useful for the next steps.

**Comment by leobalter** [comment]
features tag are used to supplement the original organization where each folder is already a feature. It's important for the runner to identify the `built-ins/Atomics` folder fundamentally provides the Atomics/SharedArrayBuffer feature, same for the `intl402` folder, where we should not be tagging everything there as Intl.

The runner should be smart enough to apply these filters properly.

**Comment by leobalter** [comment]
Also, we need to considerate a separate regular filter - not custom defined - for system/files behaviors.

```
  if (path.basename(test.location)[0] === ".") return false;

  // emacs!
  if (test.location.includes("~")) return false;
```

**Comment by leobalter** [comment]
Prepack is filtering out tests for cross realms, their filter is not precise (eliminate every file path containing `realm`) and I’m thinking in a different approach, I’d like to bikeshed some ideas

what if we include a `features: [cross-realm]`? It’s not an exact feature, but a known behavior from the spec. Although, I don’t expect every implementation to support multiple realms, so Test262 can easily tell what is expecting cross-realm behaviors, at least using the $262.createRealm

**Comment by leobalter** [comment]
feature: tail-call-optimization
folder/feature: Atomics

**Comment by leobalter** [comment]
My brain is melting down right now. It took me an hour to see the `!` in this filter:

```
test.location.includes("intl402") && !test.location.includes("/Date/prototype/to")
```

That means it filters out every path that includes intl402 but not if they also include "/Date/prototype/to"

```
 tree -if test/ | grep intl402 | grep Date/prototype/to
test/intl402/Date/prototype/toLocaleDateString
test/intl402/Date/prototype/toLocaleDateString/13.3.2_L15.js
test/intl402/Date/prototype/toLocaleString
test/intl402/Date/prototype/toLocaleString/13.3.1_L15.js
test/intl402/Date/prototype/toLocaleString/default-options-object-prototype.js
test/intl402/Date/prototype/toLocaleTimeString
test/intl402/Date/prototype/toLocaleTimeString/13.3.3_L15.js
```

**Comment by leobalter** [comment]
tests where the location has `/with/` are filtered out but they are all passing already. Also, the repl page parses it just fine, btw.

```
=== RESULTS ===
Passes: 154 / 154 (100%)
ES5 passes: 144 / 144 (100%)
ES6 passes: 10 / 10 (100%)
Skipped: 29035
Timeouts: 0
```

**Comment by leobalter** [comment]
```yaml
features:
  - tail-call-optimization
  - generators
  - default-parameters
  - Function.prototype.toString
  - SharedArrayBuffer
  - atomics
  - cross-realm
  - u180e
  - Symbol.isConcatSpreadable
esid:
  - pending
es5id:
  - 7.8.5_A1.4_T2
  - 7.8.5_A2.4_T2
  - 7.8.5_A2.1_T2
  - 7.8.5_A1.1_T2
  - 15.1.2.2_A8
  - 15.1.2.3_A6
  - 7.4_A5
  - 7.4_A6
  - 15.10.2.12_A3_T1
  - 15.10.2.12_A4_T1
  - 15.10.2.12_A5_T1
  - 15.10.2.12_A6_T1
es6id:
  - 22.1.3.1_3
flags:
  - module
  - async
location:
  - test/language/directive-prologue/
  - test/intl402/
  - test/built-ins/Function/prototype/toString/
  - test/built-ins/SharedArrayBuffer/
  - test/built-ins/Atomics/
  - test/annexB/
  - test/language/statements/with/
  - detached-buffer-after-toindex-byteoffset.js
  - test/built-ins/ArrayIteratorPrototype/next/detach-typedarray-in-progress.js
  - test/built-ins/RegExp/S15.10.2.12_A1_T1.js
  - test/built-ins/RegExp/S15.10.2.12_A2_T1.js
  - test/built-ins/RegExp/prototype/Symbol.search/lastindex-no-restore.js
  - test/built-ins/RegExp/prototype/exec/failure-lastindex-no-access.js
  - test/built-ins/RegExp/prototype/exec/success-lastindex-no-access.js
  - test/built-ins/RegExp/prototype/Symbol.match/builtin-success-u-return-val-groups.js
  - test/built-ins/decodeURI
  - test/built-ins/encodeURI
  - test/built-ins/decodeURIComponent
  - test/built-ins/encodeURIComponent
```
